name=EasyRobot
version=1.0.1
author=CVR Electrónica <develop@cvrelectronica.com>
maintainer=CVR Electrónica <develop@cvrelectronica.com>
sentence=EasyRobt es una tarjeta de desarrollo que facilita proyectos de robótica basados en Arduino.
paragraph=EasyRobot simplifica el desarrollo de proyectos de robótica al integrar todos los componentes necesarios en una sola tarjeta compatible con Arduino UNO.
category=Other
url=https://github.com/cvrelectronica/EasyRobot
architectures=avr
